### ISSUE TITLE
Display "Artist - Song name" in player from ID3 Tag

### ISSUE THREAD

**Issue by jacquesdupontd** [ltguillaume/music-folder-player#58]
Hi, 

First thank you very much for this project. I was wondering if it could be easily possible to get ID3 infos (Artist and song name mainly) and display them in the top player when playing a track ? Some downloads (like on slsk) are not composed of the Artist name in the file name and sometimes neither on the folder so we don't know which artist the track is from.

**Comment by ltguillaume** [comment]
Hi. This is beyond the scope of the project (https://github.com/ltguillaume/music-folder-player/issues/40#issuecomment-682447942).

You can already specify multiple syntaxes for pathnames, so that's about as much flexibility I want to put into this, because it's really simple to properly rename a music collection, e.g. by using MusicBrainz.

**Comment by jacquesdupontd** [comment]
Thanks for the fast reply. I totally understand and thanks for pointing me to MusicBrainz, worked wonders !

**Comment by ltguillaume** [comment]
No problem!
